[package]
name = "flex_mod_macros"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
flex_mod_macros_core.workspace = true

proc-macro-error = "1.0.4"
